config/routes.rb
Rails.application.routes.draw do
  # root to: redirect('/events')
  root 'entries#index'
  
  resources :verbs do
    resources :samples
    resources :conjungations
  end
  resources :people do
    resources :kids
    resources :parents
  end
  resources :entries do
    resources :samples
  end
end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :entry
  
  validates :de, presence: true
  validates :ru, presence: true
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:entry_id, :de, :en, :ru)
    end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.haml
= simple_form_for(@sample) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :entry
    = f.input :de
    = f.input :en
    = f.input :ru

  .form-actions
    = f.button :submit

app/views/samples/edit.html.haml
%h1 Editing sample

= render 'form'

= link_to 'Show', @sample
\|
= link_to 'Back', samples_path

app/views/samples/index.html.haml
%h1 Listing samples

%table
  %thead
    %tr
      %th Entry
      %th De
      %th En
      %th Ru
      %th
      %th
      %th

  %tbody
    - @samples.each do |sample|
      %tr
        %td= sample.entry
        %td= sample.de
        %td= sample.en
        %td= sample.ru
        %td= link_to 'Show', sample
        %td= link_to 'Edit', edit_sample_path(sample)
        %td= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Sample', new_sample_path

app/views/samples/new.html.haml
%h1 New sample

= render 'form'

= link_to 'Back', samples_path

app/views/samples/show.html.haml
%p#notice= notice

%p
  %b Entry:
  = @sample.entry
%p
  %b De:
  = @sample.de
%p
  %b En:
  = @sample.en
%p
  %b Ru:
  = @sample.ru

= link_to 'Edit', edit_sample_path(@sample)
\|
= link_to 'Back', samples_path