config/routes.rb
Rails.application.routes.draw do
  # root to: redirect('/events')
  root 'entries#index'
  
  resources :verbs do
    resources :samples
    resources :conjungations
  end
  resources :people do
    resources :kids
    resources :parents
  end
  resources :entries do
    resources :samples
  end
end

app/models/kid.rb
class Kid < ApplicationRecord
  belongs_to :person, optional: true
  
  validates :name, presence: true
  validates :year, presence: true
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
  end

  # GET /kids/1/edit
  def edit
  end

  # POST /kids
  # POST /kids.json
  def create
    @person = Person.find(params[:person_id])
    @kid = @person.kids.create(kid_params)
#    @kid = Kid.new(kid_params)
    reflect_to  pwerson_url(@person)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      params.require(:kid).permit(:person_id, :name, :nick, :year, :person_id)
    end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@person, @kid) do |f|

  .form-inputs
    = f.association :person
    = f.input :name
    = f.input :nick
    = f.input :year

    = f.hidden_field @person
  .form-actions
    = f.button :submit

app/views/kids/edit.html.haml
%h1 Editing kid

= render 'form'

= link_to 'Show', @kid
\|
= link_to 'Back', kids_path

app/views/kids/index.html.haml
%h1 Listing kids

%table
  %thead
    %tr
      %th Person
      %th Name
      %th Nick
      %th Year
      %th
      %th
      %th

  %tbody
    - @kids.each do |kid|
      %tr
        %td= kid.person
        %td= kid.name
        %td= kid.nick
        %td= kid.year
        %td= link_to 'Show', kid
        %td= link_to 'Edit', edit_kid_path(kid)
        %td= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Kid', new_kid_path

app/views/kids/new.html.haml
%h1 New kid

= render 'form'

= link_to 'Back', kids_path

app/views/kids/show.html.haml
%p#notice= notice

%p
  %b Person:
  = @kid.person
%p
  %b Name:
  = @kid.name
%p
  %b Nick:
  = @kid.nick
%p
  %b Year:
  = @kid.year

= link_to 'Edit', edit_kid_path(@kid)
\|
= link_to 'Back', kids_path