config/routes.rb
Rails.application.routes.draw do
  # root to: redirect('/events')
  root 'entries#index'
  
  resources :verbs do
    resources :samples
    resources :conjungations
  end
  resources :people do
    resources :kids
    resources :parents
  end
  resources :entries do
    resources :samples
  end
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :kids, dependent: :destroy
  accepts_nested_attributes_for :kids, allow_destroy: true, reject_if: proc {|attr| attr['name'].blank? or attr['year'].blank?}
#  accepts_nested_attributes_for :kids, allow_destroy: true, reject_if: :all.blank?
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @q = Person.ransack(params[:q])
    @people = @q.result(distinct: true)
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
    3.times do
      @person.kids.build
    end
  end

  # GET /people/1/edit
  def edit
#    3.times do
      @person.kids.build
#    end
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
#      params.require(:person).permit(:name, :profession, Kid.attribute_names.map(&:to_sym).push(:_destroy))  # not working...
      params.require(:person).permit(:name, :profession, kids_attributes: [:id, :_destroy, :name, :nick, :year])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@person) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :profession

  %h3 Kids
  %table.table
    %thead
      %tr
        %th
        %th Name
        %th Nick
        %th Year

    %tbody.fields
      = f.simple_fields_for :kids do |build|
        = render 'kid', f: build

  .form-actions
    = f.button :submit

app/views/people/_kid.html.haml
%tr
  - if f.object.persisted?
    %td
      = f.check_box :_destroy
      = f.label :_destroy, "Destroy"
      /= f.input_field :_destroy, as: :hidden
      /%button.btn.btn-dark.btn-sm= link_to 'Delete', '#'
  - else
    %td

  %td= f.input :name, label: false
  %td= f.input :nick, label: false
  %td= f.input :year, label: false

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
= search_form_for @q do |f|
  = f.label :name_or_profession_cont
  = f.search_field :name_or_profession_cont
  = f.submit
%h2 Result
%table
  %thead
    %tr
      %th Name
      %th Profession
  %tbody
    - @people.each do |person|
      %tr
        %td
          = person.name
        %td
          = person.profession

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @person.name
%p
  %b Profession:
  = @person.profession

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'Back', people_path

app/views/people/zt_index.html.erb
<%= search_form_for @q do |f| %>

  <%= f.label :name_or_profession_cont %>
  <%= f.search_field :name_or_profession_cont %>
  
  <%= f.submit %>
<% end %>

<h2>Result</h2>  
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Profession</th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td>
          <%= person.name %>
        </td>
        <td>
          <%= person.profession %>
        </td>
       </tr>
    <% end %>
  </tbody>
</table>