config/routes.rb
Rails.application.routes.draw do
  # root to: redirect('/events')
  root 'entries#index'
  
  resources :verbs do
    resources :samples
    resources :conjungations
  end
  resources :people do
    resources :kids
    resources :parents
  end
  resources :entries do
    resources :samples
  end
end

app/models/verb.rb
class Verb < ApplicationRecord
  belongs_to :group
  belongs_to :rule
  
  has_many   :examples
  has_many   :conjugations

  accepts_nested_attributes_for :examples, allow_destroy: true, 
    reject_if: proc {|attr| attr['de'].blank?}

  accepts_nested_attributes_for :conjugations, allow_destroy: true, 
    reject_if: proc {|attr| attr['present_simple'].blank? or attr['past_simple'].blank? or attr['present_perfect'].blank?}
  
  enum aux: %w(hat ist hat/ist)

  validates :infinitive, presence: true
  validates :prasens,    presence: true
  validates :simple,     presence: true
  validates :participle, presence: true
  validates :ru,         presence: true
end

app/controllers/verbs_controller.rb
class VerbsController < ApplicationController
  before_action :set_verb, only: [:show, :edit, :update, :destroy]

  # GET /verbs
  # GET /verbs.json
  def index
#   @verbs = Verb.all
    @q     = Verb.order('lower(infinitive)').ransack(params[:q])
    @verbs = @q.result(distinct: true)
  end

  # GET /verbs/1
  # GET /verbs/1.json
  def show
  end

  # GET /verbs/new
  def new
    @verb = Verb.new
    3.times do
      @verb.examples.build
    end
    6.times do
      @verb.conjugations.build
#      @personal_pronoun = PersonalPronoun.third
    end
  end

  # GET /verbs/1/edit
  def edit
    (3 - @verb.examples.count).times do
      @verb.examples.build
    end
    (6 - @verb.conjugations.count).times do
      @verb.conjugations.build
    end
  end

  # POST /verbs
  # POST /verbs.json
  def create
    @verb = Verb.new(verb_params)

    respond_to do |format|
      if @verb.save
        format.html { redirect_to @verb, notice: 'Verb was successfully created.' }
        format.json { render :show, status: :created, location: @verb }
      else
        format.html { render :new }
        format.json { render json: @verb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verbs/1
  # PATCH/PUT /verbs/1.json
  def update
    respond_to do |format|
      if @verb.update(verb_params)
        format.html { redirect_to @verb, notice: 'Verb was successfully updated.' }
        format.json { render :show, status: :ok, location: @verb }
      else
        format.html { render :edit }
        format.json { render json: @verb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verbs/1
  # DELETE /verbs/1.json
  def destroy
    @verb.destroy
    respond_to do |format|
      format.html { redirect_to verbs_url, notice: 'Verb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verb
      @verb = Verb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verb_params
      params.require(:verb).permit(:group_id, :rule_id, :infinitive, :prasens, :simple, :participle, :trxn, :ru, :en, :aux,
                                    examples_attributes: [:id, :_destroy, :de, :en, :ru],
                                    conjugations_attributes: [:id, :_destroy, :personal_pronoun, :present_simple, :past_simple, :present_perfect])
    end
end

app/helpers/verbs_helper.rb
module VerbsHelper
  def full_infinitive verb
    if verb.trxn.blank? 
      verb.infinitive
    else
      "#{verb.infinitive} [#{verb.trxn}]"
    end
  end

  # https://stackoverflow.com/questions/3863844/rails-how-to-build-table-in-helper-using-content-tag
  def display_verbs_table(columns, collection = {})

    thead = content_tag :thead do
      content_tag :tr do
        columns.collect {|column| concat content_tag(:th, column[:display_name], class: "head")}.join().html_safe
        concat content_tag :th, "Aktionen", class: "head"
        end
    end

    infinite_class  = 'bg-secondary text-light font-weight-bold'
    
    tbody = content_tag :tbody do
      collection.collect { |elem|

      participle   = "#{elem.attributes['aux']} #{elem.attributes['participle']}" 
      view_button_class = elem.examples.present? ? "btn btn-default btn-sm verb" : "btn btn-default btn-sm"

        content_tag :tr do
          concat content_tag :td, full_infinitive(elem),     class: infinite_class
          concat content_tag :td, elem.attributes['prasens']
          concat content_tag :td, elem.attributes['simple']
          concat content_tag :td, participle
          concat content_tag :td, elem.attributes['ru']
          concat content_tag :td, elem.attributes['en']
          concat content_tag :td, link_to((fa_icon "edit 1x"),    edit_verb_path(elem)), class: 'btn btn-default btn-sm'
          concat content_tag(:td, link_to((fa_icon "fas eye 1x"), verb_path(elem)),      class: view_button_class)
        end

      }.join().html_safe
    end
    content_tag :table, thead.concat(tbody), class: "table-sm table table-hover"
  end
end

app/views/verbs/_example.html.haml
%tr
  - if f.object.persisted?
    %td
      = f.check_box :_destroy
      = f.label :_destroy, "Zerstören"
  - else
    %td

  %td= f.input :de, label: false, placeholder: 'Deutsch'
  %td= f.input :ru, label: false, placeholder: 'Russisch'
  %td= f.input :en, label: false, placeholder: 'Englisch'

app/views/verbs/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@verb, class: "form-inline") do |f|
  /= f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  - flash.each do |message_type, message|
    .alert.alert-success= message

  .row
    .form-group.col-md-2
      = f.association :group, label: false, collection: Group.all.map {|g| [g.de, g.id]}, include_blank: false
    .form-group.col-md-2
      /= f.association :rule,  label: false, collection: Rule.pluck(:scheme), include_blank: false   # Not working properly??   
      = f.association :rule,  label: false, collection: Rule.all.map {|r| [r.scheme, r.id]}, include_blank: false

  .row
    .form-group.col-md-3
      = f.input :infinitive, label: false, placeholder: 'Infinitiv'
    .form-group.col-md-3
      = f.input :prasens,    label: false, placeholder: 'Präsens '
    .form-group.col-md-3
      = f.input :simple,     label: false, placeholder: 'Präteritum'
    .form-group.col-md-3
      = f.input :participle, label: false, placeholder: 'Partizip II '

  .row
    .form-group.col-md-3
      = f.input :trxn,      label: false, placeholder: 'Transkription '
    .form-group.col-md-3
      = f.input :ru,        label: false, placeholder: 'Ru'
    .form-group.col-md-3
      = f.input :en,        label: false, placeholder: 'En'
    .form-group.col-md-2
      = f.input :aux,       label: false

  %h4 Verbformen
  %table.table
    %tbody.fields

      - pp = Conjugation.personal_pronouns
      - i = 0
      = f.simple_fields_for :conjugations do |c|
        %tr
          %td= c.input :personal_pronoun, label: false, selected: pp.key(i)
          %td= c.input :present_simple,   label: false, placeholder: 'Präsens'
          %td= c.input :past_simple,      label: false, placeholder: 'Präteritum'
          %td= c.input :present_perfect,  label: false, placeholder: 'Perfekt'
          - i += 1

  %h4 Beispiele
  %table.table
    %tbody.fields
      = f.simple_fields_for :examples do |example|
        = render 'example', f: example

  .form-actions
    %button.btn.btn-primary{:type => "submit"}
      %i.fa.fa-save
        Schaffen

    = link_to verbs_path, class: "btn btn-info" do 
      = fa_icon "list"
      = "Liste"

    -#= link_to new_verb_path, class: "btn btn-dark" do
      = fa_icon "plus-square 1x"
      = "Neu"

app/views/verbs/edit.html.haml
%h1 Verb bearbeiten
= render 'form'

app/views/verbs/index.html.haml
.row
  .col-md-8
    %h1 Verben auflisten
  .col-md-2
    = link_to new_verb_path, class: "btn btn-dark" do
      = fa_icon "plus-square 1x"
      = "Neu"
 
= search_form_for @q do |f|
  = f.search_field :infinitive_or_en_or_ru_cont
  = f.submit 'suchen'
 
= display_verbs_table(                                          |
  [                                                             |
    { :name => 'infinitive', :display_name => 'Infinitiv' },    |
    { :name => 'prasens',    :display_name => 'Präsens' },      |
    { :name => 'simple',     :display_name => 'Präteritum' },   |
    { :name => 'participle', :display_name => 'Partizip II' },  |
    { :name => 'ru',         :display_name => 'Russisch' },     |
    { :name => 'en',         :display_name => 'Englisсh' },     |
  ],                                                            |
  @verbs)                                                       |
.col-md-2
  = link_to new_verb_path, class: "btn btn-dark" do
    = fa_icon "plus-square 1x"
    = "Neu"

app/views/verbs/new.html.haml
%p= notice
%h1 Neuer Verb
= render 'form'

app/views/verbs/show.html.haml
- flash.each do |message_type, message|

  .alert.alert-success= message
%h1.title
  .row
    .col-md-6
      = "#{@verb.infinitive}"
      = "[#{@verb.trxn}]" if @verb.trxn.present?
    .col-md-2.scheme
      = "  #{@verb.rule.scheme}" if (@verb.rule.scheme.present? and @verb.rule.scheme.exclude? "nicht")
%table.table.table-hover.table-bordered
  %thead.thead-dark
    %th= 'Präsens'
    %th= 'Präteritum'
    %th= 'Partizip II'
    %th= 'Gruppe'
    %th= 'Russisch'
    %th= 'Englisсh'
  %tbody.personalpronoun
    %td= @verb.prasens
    %td= @verb.simple
    %td= "#{@verb.aux} #{@verb.participle}"
    %td= @verb.group.de
    %td= @verb.ru
    %td= @verb.en

- if @verb.conjugations.present?
  %h4.italic Konjugationen
  %table.table.table-hover.table-bordered
    %thead.thead-dark
      %th= 'Personal Pronoun'
      %th= 'Präsens'
      %th= 'Präteritum'
      %th= 'Perfekt'

    - @verb.conjugations.each do |conjugation|
      %tbody.table-striped
        %td.font-weight-bold= conjugation.personal_pronoun
        %td= conjugation.present_simple
        %td= conjugation.past_simple
        %td= conjugation.present_perfect

- if @verb.examples.present?
  %h4.italic Beispiele
  %table.table.table-hover.table-bordered
    - @verb.examples.each do |example|
      %tbody
        %td.font-weight-bold= example.de
        %td= example.ru
        %td= example.en

.row
  .col-md-2
    = link_to edit_verb_path, class: "btn btn-primary" do 
      = fa_icon "edit"
      = "Bearbeiten"
  .col-md-2
    = link_to verbs_path, class: "btn btn-info" do 
      = fa_icon "list"
      = "Liste"
  .col-md-2
    = link_to new_verb_path, class: "btn btn-dark" do
      = fa_icon "plus-square 1x"
      = "Neu"